version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Pre-build started
      - chmod +x mvnw
  build:
    commands:
      - echo Building the project...
      - ./mvnw package -DskipTests
      - echo Copying appspec.yml to target directory
      - cp appspec.yml target/
      - echo Listing target directory
      - ls -al target/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/meyzieu_gym.back-0.0.1-SNAPSHOT.jar
    - target/appspec.yml
