version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-build started
  build:
    commands:
      - echo Building the project...
      - ./mvnw package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar