name: Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker compose build
      - name: Push to registry
        run: docker-compose push

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull benjaminrichard/mga-back:latest
      - name: Delete old container
        run: sudo docker rm -f mga-back-container
      - name: Run docker container
        run: |
          docker compose up -e \
          MYSQL_DATABASE= ${{ secrets.MYSQL_DATABASE }} \
          MYSQL_ROOT_PASSWORD= ${{ secrets.MYSQL_ROOT_PASSWORD }} \
          MYSQL_PASSWORD= ${{ secrets.MYSQL_PASSWORD }} \
          MYSQL_USER= ${{ secrets.MYSQL_USER }} \
          MYSQL_HOST= ${{ secrets.MYSQL_HOST }}